### ISSUE TITLE
Output shows 200 responses, while in burp/browser the actual response is 301.  Also, the proxy feature does not work with Burp.

### ISSUE THREAD

**Issue by spencer5cent** [trap-bytes/403jump#4]
[
![403jump](https://github.com/trap-bytes/403jump/assets/61186347/5a7b2aee-2b8f-4c6f-965f-77204cae8266)
](url)

As shown in the screenshot, every or many of the bypasses tried are successful, but in actuality nothing is being by passed.

As for the proxy option, since we cannot include the protocol (http), running the script fails if used with Burp.

**Comment by trap-bytes** [comment]
The tool shows the final response after following the redirect, in your case it was a 200 that's why.
In order to use Burp you don't need to specify the http protocol, just use port:ip.
You can refer to the examples in the readme.
